import type { Metadata } from "next";
import "./globals.css";
import { Inter, Geist, Covered_By_Your_Grace, Signika } from "next/font/google";
import localFont from "next/font/local";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Add different font weights if needed
});

const grace = Covered_By_Your_Grace({
  weight: "400",
  style: ["normal"],
  subsets: ["latin"], // Or other subsets you need
});

// const grace = localFont({
//   src: "./../../public/fonts/Covered_By_Your_Grace.ttf",
//   variable: "--font-grace",
//   display: "swap",
// });

const signika = Signika({
  weight: "400",
  style: ["normal"],
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Agroconnect",
  description: "Generated by agroconnect",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&family=Roboto:wght@300;400;500&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${inter.className} ${grace.className} w-full overflow-y-auto`}
      >
        <main className="w-full h-full">{children}</main>
      </body>
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body> */}
    </html>
  );
}
